mode: ContinuousDelivery
next-version: 0.1.0
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
commit-message-incrementing: Enabled
ignore:
  sha: []
increment: Patch  # Default if branch doesn't match anything

branches:
  master:
    regex: ^master$
    tag: ''                       # stable release, no prerelease
    increment: Patch              # bump patch if commits land directly on master
    source-branches: [ develop ]  # merges from develop trigger stable version

  develop:
    regex: ^develop$
    tag: alpha                     # prerelease alpha versions
    increment: Minor               # bump minor for next stable series
    source-branches: [ feature/* ] # merges from features trigger alpha increment

  feature:
    regex: ^feature[/-].*$
    tag: alpha
    increment: Inherit             # inherit develop’s alpha behavior
    source-branches: [ develop ]   # features merge into develop
