mode: ContinuousDelivery
next-version: 0.1.0
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
commit-message-incrementing: Enabled
ignore:
  sha: []

increment: Patch  # default increment if branch doesn't match

branches:
  master:
    regex: ^master$
    tag: ''             # stable releases
    increment: Minor    # bump minor when merging develop → master
    tracks-release-branches: false

  develop:
    regex: ^develop$
    tag: alpha          # alpha prereleases for next minor
    increment: Minor
    source-branches: [ master ]
