mode: ContinuousDelivery
next-version: 0.1.0
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
commit-message-incrementing: Enabled
ignore:
  sha: []
increment: Patch  # Default if branch doesn't match anything

branches:
  master:
    regex: ^master$
    tag: ''                   # stable release, no prerelease
    increment: Patch          # bump patch if commits land directly on master

  develop:
    regex: ^develop$
    tag: alpha                # prerelease alpha versions
    increment: Minor          # bump patch for each merge to develop; keeps minor stable
    source-branches: [ master ]
  feature:
    regex: ^feature[/-].*$
    tag: alpha
    increment: Inherit        # inherit develop’s alpha behavior
    source-branches: [ develop ]