mode: ContinuousDelivery
next-version: 0.1.0
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
commit-message-incrementing: Enabled
ignore:
  sha: []
increment: Patch

branches:
  master:
    regex: ^master$
    tag: ''                   # stable release, no prerelease
    increment: Patch          # bump patch if commits land directly on master
    source-branches: [ develop ] # only merges from develop affect master version

  develop:
    regex: ^develop$
    tag: alpha                # prerelease alpha versions
    increment: Minor          # bump minor on each merge into develop
    source-branches: [ feature/* ] # merges from feature branches trigger alpha

  feature:
    regex: ^feature[/-].*$
    tag: alpha
    increment: Inherit        # inherit develop’s alpha behavior
    source-branches: [ develop ]
