mode: ContinuousDelivery
next-version: 0.2.0
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
commit-message-incrementing: Enabled
ignore:
  sha: []
increment: Patch  # default if branch doesn't match anything

branches:
  master:
    regex: ^master$
    tag: ''                       # stable release
    increment: Patch
    source-branches: [ develop ]  # merges from develop trigger stable version

  develop:
    regex: ^develop$
    tag: alpha                     # prerelease alpha versions
    increment: Minor
    source-branches: [ feature ]  # MUST match branch name type exactly

  feature:
    regex: ^feature[/-].*$
    tag: alpha
    increment: Inherit
    source-branches: [ develop ]
