name: CoolJob
on: workflow_dispatch

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "${GITHUB_CONTEXT}"
  job-2:
    runs-on: ubuntu-latest
    needs:
      - job-1
    steps:
      - name: Hello World
        run: |
          echo "Hello World from job 2"
          echo "Another message on a new line"

  job-3:
    runs-on: ubuntu-latest
    needs:
      - job-2
    steps:
      - name: Hello World
        run: |
          echo "Hello World from job 3"
          echo "Another message on a new line"
