name: CoolJob
on: workflow_dispatch

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: |
          echo "Hello World from job 1"
          echo "Another message on a new line"
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: |
          echo "Hello World from job 2"
          echo "Another message on a new line"

  job-3:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: |
          echo "Hello World from job 3"
          echo "Another message on a new line"
